global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "otel-collector-iad"
    static_configs:
      - targets: ["otel-collector-iad:8889"]

  - job_name: "otel-collector-sfo"
    static_configs:
      - targets: ["otel-collector-sfo:8890"]

  - job_name: "clickhouse"
    static_configs:
      - targets: ["clickhouse:9363"]

  - job_name: "kafka"
    static_configs:
      - targets: ["kafka:9092"]
