{
 "title": "Simple Kafka Monitoring",
 "tags": [
  "kafka",
  "simple"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active Brokers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kafka_brokers" }
   ]
  },
  {
   "title": "Messages per Topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_topic_partition_current_offset{topic=~\".*traces.*\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Consumer Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "kafka_consumergroup_lag_sum", "legendFormat": "{{consumergroup}} - {{topic}}" }
   ]
  },
  {
   "title": "Topic Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_topic_partition_current_offset{topic=~\".*traces.*\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}