apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse
    access: proxy
    jsonData:
      defaultDatabase: traces
      host: clickhouse
      port: 9000
      username: admin
      tlsSkipVerify: false
    secureJsonData:
      password: password

  - name: ClickHouse-HTTP
    type: simpod-json-datasource
    uid: clickhouse-http
    url: http://clickhouse:8123
    access: proxy
    basicAuth: true
    basicAuthUser: admin
    isDefault: false
    jsonData: {}
    secureJsonData:
      basicAuthPassword: password
