apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    url: http://clickhouse:8123
    access: proxy
    basicAuth: false
    isDefault: true
    jsonData:
      username: admin
      defaultDatabase: traces
    secureJsonData:
      password: password
